{{- if and .Values.uniplusApiSelecao.enabled .Values.uniplusApiSelecao.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uniplusApiSelecao.serviceAccountName" . }}
  labels:
    {{- include "uniplusApiSelecao.labels" . | nindent 4 }}
{{- end }}
