{{- if and .Values.serviceMonitor.enabled .Values.vaultTransit.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-vault-transit
  labels:
    app.kubernetes.io/name: vault-transit
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: uniplus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultTransit
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: https-internal
      path: /v1/sys/metrics
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      params:
        format:
          - prometheus
{{- end }}
