{{- if and .Values.unifesspaGeoApi.enabled .Values.unifesspaGeoApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unifesspaGeoApi.serviceAccountName" . }}
  labels:
    {{- include "unifesspaGeoApi.labels" . | nindent 4 }}
{{- end }}
