{{- if and .Values.redisUi.enabled .Values.redisUi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redisUi.serviceAccountName" . }}
  labels:
    {{- include "redisUi.labels" . | nindent 4 }}
{{- end }}
