{{- if and .Values.apicurioRegistry.enabled .Values.apicurioRegistry.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "apicurioRegistry.fullname" . }}
  labels:
    {{- include "apicurioRegistry.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.apicurioRegistry.ingress.entryPoint }}
  routes:
    - match: Host(`{{ .Values.apicurioRegistry.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "apicurioRegistry.fullname" . }}
          port: 8080
          # Apicurio UI requer X-Forwarded-{Host,Proto} para Quarkus OIDC
          # redirect URI bater com o registrado no realm. Traefik faz por
          # default — não precisamos de middleware extra.
  {{- if .Values.apicurioRegistry.ingress.tls.enabled }}
  tls:
    secretName: {{ .Values.apicurioRegistry.ingress.tls.secretName | default (printf "%s-tls" (include "apicurioRegistry.fullname" .)) }}
  {{- end }}
{{- end }}
