{{- if and .Values.kafkaUi.enabled .Values.kafkaUi.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "kafkaUi.fullname" . }}
  labels:
    {{- include "kafkaUi.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.kafkaUi.ingress.entryPoint }}
  routes:
    - match: Host(`{{ .Values.kafkaUi.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "kafkaUi.fullname" . }}
          port: 8080
          # AKHQ não roda atrás de path prefix — proxy precisa preservar
          # X-Forwarded-{Host,Proto} para Micronaut OIDC redirect URI bater
          # com o registrado no Keycloak. Traefik faz isso por default.
  {{- if .Values.kafkaUi.ingress.tls.enabled }}
  tls:
    secretName: {{ .Values.kafkaUi.ingress.tls.secretName | default (printf "%s-tls" (include "kafkaUi.fullname" .)) }}
  {{- end }}
{{- end }}
