{{- if and .Values.kafkaUi.enabled .Values.kafkaUi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafkaUi.serviceAccountName" . }}
  labels:
    {{- include "kafkaUi.labels" . | nindent 4 }}
{{- end }}
