{{- if .Values.uniplusWeb.enabled -}}
{{- if .Values.uniplusWeb.serviceAccount.create -}}
{{- range $app, $cfg := .Values.uniplusWeb.apps -}}
{{- if $cfg.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uniplusWeb.serviceAccountName" (dict "ctx" $ "app" $app) }}
  labels:
    {{- include "uniplusWeb.labels" (dict "ctx" $ "app" $app) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
