{{- if and .Values.uniplusApiPortal.enabled .Values.uniplusApiPortal.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uniplusApiPortal.serviceAccountName" . }}
  labels:
    {{- include "uniplusApiPortal.labels" . | nindent 4 }}
{{- end }}
