# Default values para uniplus-api-selecao
# TODO: implementar conforme estrutura do uniplus-web

replicas: 2

image:
  registry: ghcr.io
  repository: unifesspa-edu-br/uniplus-api-selecao
  pullPolicy: IfNotPresent
  tag: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

commonLabels:
  app.kubernetes.io/part-of: uniplus
  app.kubernetes.io/component: api
