apiVersion: v2
name: keycloak-replica
description: Réplica local do Keycloak institucional para autenticação
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - uniplus
  - auth
  - unifesspa
home: https://github.com/unifesspa-edu-br/uniplus-infra
sources:
  - https://github.com/unifesspa-edu-br/uniplus-infra
maintainers:
  - name: CTIC UNIFESSPA
    email: jeferson.ferreira@unifesspa.edu.br
annotations:
  category: auth
  licenses: MIT
