{{- if and .Values.uniplusApiIngresso.enabled .Values.uniplusApiIngresso.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "uniplusApiIngresso.serviceAccountName" . }}
  labels:
    {{- include "uniplusApiIngresso.labels" . | nindent 4 }}
{{- end }}
