{{- if and .Values.keycloak.enabled .Values.keycloak.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak-replica.serviceAccountName" . }}
  labels:
    {{- include "keycloak-replica.labels" . | nindent 4 }}
{{- end }}
